# Generated by Django 3.0.2 on 2020-01-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_listitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
