# Generated by Django 3.0.2 on 2020-01-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20200127_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
