# Generated by Django 3.0.2 on 2020-01-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20200127_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='school',
        ),
        migrations.AddField(
            model_name='list',
            name='school',
            field=models.ManyToManyField(blank=True, null=True, to='lists.School'),
        ),
    ]
