# Generated by Django 3.0.2 on 2020-01-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_auto_20200127_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='school',
        ),
        migrations.AddField(
            model_name='list',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.School'),
        ),
    ]
