# Generated by Django 3.0.2 on 2020-02-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_list_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='seller_status',
            field=models.CharField(choices=[('recibida_pagada', 'Recibida y pagada'), ('recibida_no_pagada', 'Recibida pero no pagada'), ('en_revision', 'En revision'), ('en_camino', 'En camino'), ('entregada', 'Entregada'), ('cancelada', 'Cancelada')], default='recibida_no_pagada', max_length=20),
        ),
    ]
