# Generated by Django 3.0.2 on 2020-02-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_list_list_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='seller_status',
            field=models.CharField(choices=[('Recibida y pagada', 'Recibida y pagada'), ('Recibida pero no pagada', 'Recibida pero no pagada'), ('En revision', 'En revision'), ('Lista pedida', 'Lista pedida'), ('En camino', 'En camino'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada')], default='En revision', max_length=40),
        ),
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.CharField(choices=[('Recibida y pagada', 'Recibida y pagada'), ('Recibida pero no pagada', 'Recibida pero no pagada'), ('En revision', 'En revision'), ('Lista pedida', 'Lista pedida'), ('En camino', 'En camino'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada')], default='Recibida pero no pagada', max_length=40),
        ),
    ]
