# Generated by Django 3.0.2 on 2020-01-29 15:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='conf_num',
            field=models.CharField(default=123456, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=datetime.datetime(2020, 1, 29, 15, 52, 24, 329779, tzinfo=utc), max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
