# Generated by Django 3.0.2 on 2020-01-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='reference',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='shipping_department',
            new_name='address_reference',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='dni',
            new_name='cedula_ruc',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='shipping_district',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='shipping_province',
            new_name='shipping_canton',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_parroquia',
            field=models.CharField(default='Parroquia1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='shipping_provincia',
            field=models.CharField(default='Pichincha', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
