# Generated by Django 3.0.2 on 2020-01-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20200111_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, default=307030, max_length=30),
            preserve_default=False,
        ),
    ]
