# Generated by Django 3.0.2 on 2020-01-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20200129_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='conf_num',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
