# Generated by Django 3.0.2 on 2020-02-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_auto_20200129_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shipping_canton',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipping_parroquia',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='shipping_provincia',
        ),
    ]
