# Generated by Django 3.0.2 on 2020-01-15 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='system_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='system_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='system_id',
            field=models.CharField(default='A1', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='system_id',
            field=models.CharField(default='A2', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
