# Generated by Django 3.0.2 on 2020-01-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
    ]
