# Generated by Django 3.0.2 on 2020-02-18 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200215_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productphoto',
            options={'verbose_name': 'Foto de Producto', 'verbose_name_plural': 'Fotos de Productos'},
        ),
    ]
